[build]
command = "npm install --legacy-peer-deps && npm run build"
publish = "build"

[build.environment]
CI = ""

[functions]
directory = "netlify/functions"

[dev]
command = "npm run start"
port = 8888
targetPort = 3000
publish = "build"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200